name: Tonamel Notify

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Packages
        run: pip install discord.py playwright

      - name: Install Playwright Browsers
        run: python -m playwright install chromium --with-deps

      - name: Run Bot
        run: python bot/main.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}